### ISSUE TITLE
crash due to Siema instance doesn't have`removeAllListeners()`

### ISSUE THREAD

**Issue by passerbyid** [lexzhukov/ngx-siema#18] opened 2017-04-04 06:06 UTC
in `ngx-siema.component.ts`:
```javascript
ngOnDestroy() {
   this.instance.removeAllListeners();
   this.instance.destroy();
   this.instance = null;
 }
```
When component is on destroy, call `this.instance.removeAllListeners()` will crash the app due to Siema instance doesn't have`removeAllListeners()`.

I don't know where is `removeAllListeners()` defined and what is it's purpose, but if remove this line, everything looks fine to me.

**Comment by lexzhukov** [comment] 2017-04-04 08:22
@passerbyid thanks for your bug report. I will review your PR.

**Comment by lexzhukov** [comment] 2017-04-21 16:51
The bug is fixed in https://github.com/lexzhukov/ngx-siema/commit/09885cc143c3a09d9f42c4011a39bbaf1d9ccbcd. Today I will publish an updated package.

**Comment by vlyamzin** [comment] 2017-05-25 15:50
@lexzhukov Looks like the issue is still present. For me it occurs on every route change.

Here is the [plunker](https://plnkr.co/edit/QvbdRjbjmsJwB68yOwQy?p=preview)

**Comment by cg50x** [comment] 2017-06-05 01:57
@lexzhukov Seeing this issue as well. I've looked at the code in siema js. It looks like removing the call to `removeAllListeners()` should fix it.

**Comment by omobono** [comment] 2017-06-22 15:47
Me too.

**Comment by Justinemmerich** [comment] 2017-06-28 08:18
Please fix this error asap, thx

**Closed** 2017-07-01 19:39 UTC
Labels: bug
